### PR TITLE
Add proxy auth

### PR DESCRIPTION
**Pull request by masakura**
I'm working in an environment where there is an authenticated proxy. 
Fix authentication information to pass to the proxy.

### CODE REVIEW

**Comment by kevva** [comment]
Just pass `{proxy: {proxyAuth: 'auth'}}` to the options.

**Comment by masakura** [comment]
Thank you tell me a good way. But, it did not work it's that way.

``` javascript
var agent = require('caw')('http://proxy.host.example.com:8080', {
    proxy: {
        proxyAuth: 'hoge'
    }
});

console.log(agent.options);
```

I ran this script. but, results were not set proxy information well.

```
{ proxy: { proxyAuth: 'hoge' } }
```

This PR, the kevva/download#64 in my environment is one of the reasons for not working.

Would you merge?

**Comment by shinnn** [comment]
Fixed in https://github.com/kevva/caw/pull/9. Seems the author changed his mind.

Thanks for the contribution, @masakura.

**Comment by masakura** [comment]
I tested it with authentication proxy. It works normally.

I'm happy!

Thanks!

**Pull request closed without merging**
